version: "3.8"

services:
  db:
    image: postgres:16
    container_name: prodapp_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d:ro
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: prodapp_pgadmin
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data:
